-- Add admin management columns to sellers table
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS revoked_by UUID REFERENCES sellers(id) ON DELETE SET NULL;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS revoke_reason TEXT;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS restored_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS restored_by UUID REFERENCES sellers(id) ON DELETE SET NULL;